"""
This is a setup.py script generated by py2app specifically for macOS builds.
"""

from setuptools import setup

APP = ['tda_processing_app/main.py']
DATA_FILES = [
    ('fonts', ['fonts/SF-Pro-Regular.otf', 'fonts/SF-Pro.ttf']),
]
OPTIONS = {
    'argv_emulation': True,
    'packages': ['PyQt5', 'numpy', 'scipy', 'matplotlib', 'skimage', 'networkx', 'PIL', 'tifffile'],
    'iconfile': 'app_icon.icns',  # You'll need to create this
    'plist': {
        'CFBundleName': 'TDA Processing App',
        'CFBundleDisplayName': 'TDA Processing App',
        'CFBundleGetInfoString': "Processing app for microscopy images",
        'CFBundleIdentifier': "com.yourdomain.tda-processing-app",
        'CFBundleVersion': "1.0.0",
        'CFBundleShortVersionString': "1.0.0",
        'NSHumanReadableCopyright': "Copyright © 2024, Your Name, All Rights Reserved"
    }
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
